web/router.ex
defmodule CsvUpload.Router do
  use CsvUpload.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CsvUpload do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    post "/csv", CsvController, :upload
  end

  # Other scopes may use custom stacks.
  # scope "/api", CsvUpload do
  #   pipe_through :api
  # end
end

lib/csv_import/contact.ex
defmodule CsvImport.Contact do
  alias CsvUpload.Contact, as: Contact
  alias CsvUpload.Repo, as: Repo

  def create(data) do
    changeset = Contact.changeset(%Contact{}, _format(data))
    {status, changeset} = Repo.insert(changeset)
  end

  defp _format(data) do
    %{
      title: data["title"],
      first_name: data["firstname"],
      last_name: data["lastname"],
      middle_name: data["middlename"],
      suffix: data["suffix"],
      address: _extract_address(data),
      company: data["company"],
      primary_phone: data["daytime_phone"],
      mobile_phone: data["mobile_phone"],
      email: data["email"]
    }
  end

  defp _extract_address(data) do
    Enum.join([
      data["address1"],
      data["address2"],
      data["city"],
      data["state"],
      data["country"],
      data["zipcode"]
    ], " ")
  end
end

lib/csv_upload/endpoint.ex
defmodule CsvUpload.Endpoint do
  use Phoenix.Endpoint, otp_app: :csv_upload

  socket "/socket", CsvUpload.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :csv_upload, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_csv_upload_key",
    signing_salt: "W3P6RBA6"

  plug CsvUpload.Router
end

lib/csv_upload/repo.ex
defmodule CsvUpload.Repo do
  use Ecto.Repo, otp_app: :csv_upload
end

web/models/contacts.ex
defmodule CsvUpload.Contact do
  use CsvUpload.Web, :model

  schema "contacts" do
    field :title, :string
    field :first_name, :string
    field :last_name, :string
    field :middle_name, :string
    field :suffix, :string
    field :company, :string
    field :address, :string
    field :primary_phone, :string
    field :mobile_phone, :string
    field :email, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :first_name, :last_name, :middle_name, :suffix, :company, :address, :primary_phone, :mobile_phone, :email])
    |> validate_required([:first_name, :last_name, :address])
  end
end

web/controllers/csv_controller.ex
defmodule CsvUpload.CsvController do
  use CsvUpload.Web, :controller

  def upload(conn, %{ "csv_upload" => upload_params }) do
    csv = upload_params["csv"]
    CsvImport.import(%{ csv_file: csv })
    conn
      |> put_flash(:info, 'successfully uploaded csv')
      |> redirect(to: page_path(conn, :index))
  end
end

web/controllers/page_controller.ex
defmodule CsvUpload.PageController do
  use CsvUpload.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/error_view.ex
defmodule CsvUpload.ErrorView do
  use CsvUpload.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule CsvUpload.LayoutView do
  use CsvUpload.Web, :view
end

web/views/page_view.ex
defmodule CsvUpload.PageView do
  use CsvUpload.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Demo</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <h1>Upload CSV Demo</h1>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Please Select a valid CSV file to process</h2>
  <%= form_for @conn, csv_path(@conn, :upload), [name: :csv_upload, method: :post, multipart: true], fn f -> %>
    <%= file_input f, :csv, [accept: '.csv'] %>
    <%= submit "Upload" %>
  <% end %>
</div>